name: Teleport
main: com.jseb.teleport.Teleport
version: 3.1
author: tills13

commands:
  spawn:
    description: teleport to spawn
    usage: /<command>
  back:
    description: teleport to previous location
    usage: /<command>
  home:
    description: commands dealing with homes
    usage: '/<command> [set <name> | send <player> <home> | teleport <name> | remove <name> | rename <name> <new name> | <player> <name> | list]'
  accept:
    description: authorize teleportation to your home or person
    usage: '/<command>'
  teleport:
    description: teleport to another player
    usage: '/<command> <player>'
  area:
    description: commands dealing with areas
    usage: '/<command> [set <name> | send <player> <area> | [teleport | teleporta] <name | alias> | remove <name> | rename <name> <new name> | list]'
  death:
    description: teleport to where you died
    usage: '/<command>'
  bed: 
    description: teleport to your bed location
    usage: '/<command>'
  request: 
    description: commands dealing with managing requests
    usage: '/<command> [accept <name> | deny <name> | list]'